DJLNET.WebMvc/Controllers/NavigateController.cs
using DJLNET.ApplicationService.Interfaces;
using DJLNET.WebCore.Mvc;
using DJLNET.WebCore.Security;
using DJLNET.WebMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DJLNET.Model.Entities;
using DJLNET.Core.Extension;
using AutoMapper;
using System.Reflection;
using DJLNET.WebMvc.Extensions;

namespace DJLNET.WebMvc.Controllers
{
    /// <summary>
    /// 网站全局菜单导航管理
    /// </summary>
    public class NavigateController : BaseController
    {
        private readonly INavigateService _service;
        private readonly IMapper _mapper;
        public NavigateController(INavigateService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        [HttpGet]
        [MenuNavigate]
        public ActionResult Index()
        {
            var navigateViewModels = _mapper.Map<IEnumerable<NavigateViewModel>>(_service.GetAll());
            var sortedNavigates = SortNavigate(navigateViewModels);
            return View(sortedNavigates);
        }

        private IEnumerable<NavigateViewModel> SortNavigate(IEnumerable<NavigateViewModel> source)
        {
            var result = new List<NavigateViewModel>();
            var orders = source.OrderBy(x => x.SortOrder);
            var roots = orders.Where(x => x.ActionName.IsNullOrEmpty() && x.ControllerName.IsNullOrEmpty() && !x.ParentID.HasValue);
            foreach (var root in roots)
            {
                result.Add(root);
                if (source.Any(x => x.ParentID.HasValue && x.ParentID.Value == root.ID))
                    LoadChildren(result, root, orders);
            }
            return result;
        }

        private void LoadChildren(List<NavigateViewModel> result, NavigateViewModel item, IEnumerable<NavigateViewModel> orders)
        {
            var childs = orders.Where(x => x.ParentID.HasValue && x.ParentID.Value == item.ID);
            if (childs.Any())
            {
                foreach (var child in childs)
                {
                    result.Add(child);
                    LoadChildren(result, child, orders);
                }
            }
        }

        [HttpGet]
        public PartialViewResult Add()
        {
            var navigateViewModels = _mapper.Map<IEnumerable<NavigateViewModel>>(_service.GetAll());
            NavigateAddViewModel temp = new NavigateAddViewModel();
            temp.NavigateViewModels = SortNavigate(navigateViewModels);
            temp.Controllers = GetAllController();
            return PartialView("~/Views/Navigate/_AddEditPage.cshtml", temp);
        }

        private static IEnumerable<string> GetAllController()
        {
            var types = Assembly.GetExecutingAssembly().GetTypes().Where(x => x.IsSubclassOf(typeof(BaseController)))
                .Where(x => x.GetMethods(BindingFlags.Public | BindingFlags.Instance).Any(z => z.IsDefined(typeof(HttpGetAttribute), true) && z.IsDefined(typeof(MenuNavigateAttribute), true)));
            var result = types.Select(x => x.Name.TrimEnd("Controller"));
            return result;
        }

        [HttpPost, ActionAuthorization("NavigateAdd")]
        public ActionResult GetActionByController(string controllerName)
        {
            var controlType = Assembly.GetExecutingAssembly().GetTypes().Where(x => x.IsSubclassOf(typeof(BaseController))).Single(x => x.Name.StartsWith(controllerName));
            var actions = controlType.GetMethods(BindingFlags.Public | BindingFlags.Instance).Where(x => x.IsDefined(typeof(HttpGetAttribute), true) && x.IsDefined(typeof(MenuNavigateAttribute), true));
            var result = actions.Select(x => x.Name);
            return PartialView("~/Views/Navigate/_AddActionSelect.cshtml", result);
        }

        [HttpPost, ActionAuthorization("NavigateAdd")]
        public ActionResult Add(NavigateModel model)
        {
            return null;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost, ActionAuthorization("NavigateEdit")]
        public ActionResult Edit(NavigateModel model)
        {
            return null;
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            return null;
        }
    }
}

DJLNET.WebMvc/Controllers/RoleController.cs
using DJLNET.ApplicationService.Interfaces;
using DJLNET.Core.Paging;
using DJLNET.Model.Entities;
using DJLNET.Repository.Interfaces;
using DJLNET.WebCore.Mvc;
using DJLNET.WebMvc.Extensions;
using DJLNET.WebMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using DJLNET.Core.Extension;
using AutoMapper;
using System.Net;
using DJLNET.WebCore.Security;
using LinqKit;

namespace DJLNET.WebMvc.Controllers
{
    public class RoleController : BaseController
    {
        private readonly IRoleService _service;
        private readonly IPermissionService _permissionService;
        private IMapper _mapper;
        public RoleController(IRoleService service, IPermissionService permissionService, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
            _permissionService = permissionService;
        }

        [HttpGet]
        [MenuNavigate]
        public ActionResult Index()
        {
            return View();
        }

        [ActionAuthorization("RoleIndex")]
        public JsonResult GetPagingData(RoleQuery query)
        {
            Expression<Func<Role, bool>> condition = x => !x.IsDeleted;
            Expression<Func<Role, bool>> merge = null;
            if (!string.IsNullOrWhiteSpace(query.Name))
            {
                var name = query.Name;
                merge = f => condition.Invoke(f) && f.Name.Contains(name);
            }
            IPagedList<Role> data = _service.PagingQuery(merge == null ? condition : merge, (query.Start / query.Length) + 1, query.Length, query.OrderBy, query.OrderDir == DataTablesOrderDir.Desc);
            return DataTablesExtensions.DataTablesJsonResult(
                query.Draw,
                data.Total,
                data.Total,
                _mapper.Map<IReadOnlyList<Role>, IReadOnlyList<RoleViewModel>>(data.Rows)
            );
        }


        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost,ActionAuthorization("RoleAdd")]
        public ActionResult Add(RoleModel model)
        {
            return null;
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost,ActionAuthorization("RoleEdit")]
        public ActionResult Edit(RoleModel model)
        {
            return null;
        }

        [HttpPost]
        public ActionResult Delete(int roleId)
        {
            return null;
        }

        [HttpPost]
        [ActionName("GetRolePermissions"), ActionAuthorization("RoleAuth")]
        public PartialViewResult RolePermission(int roleId)
        {
            var role = _service.Get(roleId);
            if (role.IsDeleted) throw new Exception("试图获取一个已删除角色的权限");
            var groups = _permissionService.GetAll().GroupBy(x => x.Category);
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var group in groups)
            {
                SelectListGroup temp = new SelectListGroup() { Name = group.Key };
                list.AddRange(group.Select(x => new SelectListItem()
                {
                    Group = temp,
                    Text = x.Description,
                    Value = x.ID.ToString(),
                    Selected = role.Permissions.Any(z => z.ID == x.ID)
                }));
            }
            return PartialView("/Views/Role/_RolePermission.cshtml", list);
        }

        [HttpPost, ActionName("Auth")]
        public ActionResult SetRolePermissions(int roleId, IEnumerable<int> permissionIds)
        {
            _service.SetPermissions(roleId, permissionIds ?? new List<int>(), WorkConext.CurrentUser.Name);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

DJLNET.WebMvc/Controllers/UserController.cs
using DJLNET.ApplicationService.Interfaces;
using DJLNET.Model.Entities;
using DJLNET.WebCore.Mvc;
using DJLNET.WebCore.Security;
using DJLNET.WebMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using DJLNET.Core.Extension;
using AutoMapper;
using System.Net;
using DJLNET.WebMvc.Extensions;

namespace DJLNET.WebMvc.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserService _service;
        private readonly IMapper _mapper;
        private readonly IRoleService _roleService;
        public UserController(IUserService service, IMapper mapper, IRoleService roleService)
        {
            _service = service;
            _mapper = mapper;
            _roleService = roleService;
        }

        [HttpGet]
        [MenuNavigate]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost, ActionAuthorization("UserIndex")]
        public ActionResult GetUserPagerData(int limit, int offset, string username, string sort, string order)
        {
            Expression<Func<User, bool>> condition = null;
            if (!username.IsNullOrWhiteSpace())
                condition = x => x.Name.Contains(username);
            int pagenum = offset / limit + 1;
            if (pagenum == 0) pagenum = 1;
            var data = _service.PagingQuery(condition, pagenum, limit, sort, order == "desc" ? true : false);
            return Json(new { total = data.Total, rows = _mapper.Map<IEnumerable<UserViewModel>>(data.Rows) });
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost, ActionAuthorization("UserAdd")]
        public ActionResult Add(UserModel model)
        {
            return null;
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost, ActionAuthorization("UserEdit")]
        public ActionResult Edit(UserModel model)
        {
            return null;
        }

        [HttpPost]
        public ActionResult Delete(int userId)
        {
            return null;
        }

        [HttpPost, ActionName("Auth")]
        public ActionResult SetUserRoles(int userId, IEnumerable<int> roleIds)
        {
            _service.SetRoleList(userId, roleIds ?? new List<int>(), WorkConext.CurrentUser.Name);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost, ActionAuthorization("UserAuth")]
        public ActionResult GetUserRoleList(int userId)
        {
            var user = _service.Get(userId);
            user.Roles = user.Roles.ToList();
            List<SelectListItem> list = new List<SelectListItem>();
            var allRoles = _roleService.Find(x => x.IsActive && !x.IsDeleted);
            foreach (var x in allRoles)
            {
                SelectListItem item = new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.ID.ToString(),
                    Selected = user.Roles.Any(z => z.ID == x.ID)
                };
                list.Add(item);
            }
            return PartialView("/Views/User/_UserRole.cshtml", list);
        }
    }
}

DJLNET.WebMvc/Views/Shared/Ace/_BtnBar.cshtml
<div id="toolbar" class="btn-group-lg">
    <button id="btn_add" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新增
    </button>
    <button id="btn_info" type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>查看
    </button>
    <button id="btn_edit" type="button" class="btn btn-warning">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>修改
    </button>
    <button id="btn_delete" type="button" class="btn btn-danger">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除
    </button>
    <button id="btn_auth" type="button" class="btn btn-success">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>分配角色
    </button>
</div>

DJLNET.WebMvc/Views/Shared/Ace/_Layout.cshtml
@using StackExchange.Profiling;
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>后台管理系统-控制台</title>
    <meta name="keywords" content="后台管理系统,控制台,Ace模板" />
    <meta name="description" content="后台管理系统,控制台,Ace模板" />

    @*引用基本css*@
    @Styles.Render("~/bundles/css")

    <!--[if IE 7]>
          <link rel="stylesheet" href="@Url.Content("~/Content/Ace/assets/css/font-awesome-ie7.min.css")" />
    <![endif]-->
    <!-- fonts -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <!--加载ace样式-->
    @Styles.Render("~/bundles/acecss")

    <!--[if lte IE 8]>
      <link rel="stylesheet" href="@Url.Content("~/Content/Ace/assets/css/ace-ie.min.css")" />
    <![endif]-->

    <script src="~/Content/Ace/assets/js/ace-extra.min.js"></script>

    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Content/Ace/assets/js/html5shiv.js")"></script>
        <script src="@Url.Content("~/Content/Ace/assets/js/respond.min.js")"></script>
    <![endif]-->

    <link href="~/DJLContent/sweetalert.css" rel="stylesheet" />

    @RenderSection(name: "header", required: false)
</head>
<body>

    @{  Html.RenderPartial("~/Views/Shared/Ace/_Navbar.cshtml"); }

    <div class="main-container" id="main-container">
        <script type="text/javascript">
            try { ace.settings.check('main-container', 'fixed') } catch (e) { }
        </script>

        <div class="main-container-inner">
            <a class="menu-toggler" id="menu-toggler" href="#">
                <span class="menu-text"></span>
            </a>

            @{ Html.RenderPartial("~/Views/Shared/Ace/_Menubar.cshtml"); }

            <div class="main-content">
                <div class="breadcrumbs" id="breadcrumbs">
                    <script type="text/javascript">
                        try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
                    </script>

                    <ul class="breadcrumb">
                        <li>
                            <i class="icon-home home-icon"></i>
                            <a href="#">首页</a>
                        </li>
                        <li class="active">系统管理</li>
                    </ul><!-- .breadcrumb -->

                    <div class="nav-search" id="nav-search">
                        <form class="form-search">
                            <span class="input-icon">
                                <input type="text" placeholder="搜索 ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                                <i class="icon-search nav-search-icon"></i>
                            </span>
                        </form>
                    </div><!-- #nav-search -->
                    <div id="page_content" class="page-content">
                        @RenderBody()
                    </div><!-- /.page-content -->
                </div>
            </div><!-- /.main-content -->


            <div class="ace-settings-container" id="ace-settings-container">
                <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                    <i class="icon-cog bigger-150"></i>
                </div>

                <div class="ace-settings-box" id="ace-settings-box">
                    <div>
                        <div class="pull-left">
                            <select id="skin-colorpicker" class="hide">
                                <option data-skin="default" value="#438EB9">#438EB9</option>
                                <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                            </select>
                        </div>
                        <span>&nbsp; 选择皮肤</span>
                    </div>

                    <div>
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
                        <label class="lbl" for="ace-settings-navbar"> 固定导航条</label>
                    </div>

                    <div>
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
                        <label class="lbl" for="ace-settings-sidebar"> 固定滑动条</label>
                    </div>

                    <div>
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
                        <label class="lbl" for="ace-settings-breadcrumbs">固定面包屑</label>
                    </div>

                    <div>
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
                        <label class="lbl" for="ace-settings-rtl">切换到左边</label>
                    </div>

                    <div>
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
                        <label class="lbl" for="ace-settings-add-container">
                            切换窄屏
                            <b></b>
                        </label>
                    </div>
                </div>
            </div><!-- /#ace-settings-container -->
        </div><!-- /.main-container-inner -->

        <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
            <i class="icon-double-angle-up icon-only bigger-110"></i>
        </a>
    </div><!-- /.main-container -->
    @*引入基本js*@
    <!--[if !IE]> -->
    <script src="@Url.Content("~/Content/Ace/assets/js/jquery-2.0.3.min.js")"></script>
    <!-- <![endif]-->
    <!--[if lt IE]>
       <script src="@Url.Content("~/Content/Ace/assets/js/jquery-1.10.2.min.js")"></script>
    <![endif]-->

    <script type="text/javascript">
        if ("ontouchend" in document) document.write("<script src='~/Content/Ace/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>

    @Scripts.Render("~/bundles/acejs")

    <script src="~/DJLContent/sweetalert.min.js"></script>

    <script src="~/Content/Ace/aceinit.js"></script>

    @RenderSection(name: "footer", required: false)

    @Scripts.Render("~/bundles/jqueryvalidate")

    @*MiniProfiler配置*@
    @MiniProfiler.RenderIncludes()



</body>
</html>

DJLNET.WebMvc/Views/Shared/Ace/_LoginLayout.cshtml
@using StackExchange.Profiling;
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>DJL - Ace Login</title>
    @*引用基本css*@
    @Styles.Render("~/bundles/css")

    <!--[if IE 7]>
          <link rel="stylesheet" href="@Url.Content("~/Content/Ace/assets/css/font-awesome-ie7.min.css")" />
    <![endif]-->

    @Styles.Render("~/bundles/acecss")

    <!--[if lte IE 8]>
      <link rel="stylesheet" href="@Url.Content("~/Content/Ace/assets/css/ace-ie.min.css")" />
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Content/Ace/assets/js/html5shiv.js")"></script>
        <script src="@Url.Content("~/Content/Ace/assets/js/respond.min.js")"></script>
    <![endif]-->

    @RenderSection(name: "header", required: false)
</head>
<body class="login-layout" style="background-color:darkslategrey;">
    @RenderBody()
    @*引入基本js*@

    <!--[if !IE]> -->
    <script src="@Url.Content("~/Content/Ace/assets/js/jquery-2.0.3.min.js")"></script>
    <!-- <![endif]-->
    <!--[if lt IE]>
       <script src="@Url.Content("~/Content/Ace/assets/js/jquery-1.10.2.min.js")"></script>
    <![endif]-->

    <script type="text/javascript">
        if ("ontouchend" in document) document.write("<script src='~/Content/Ace/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>

    @RenderSection(name: "footer", required: false)

    @Scripts.Render("~/bundles/jqueryvalidate")

    @*MiniProfiler配置*@
    @MiniProfiler.RenderIncludes();

</body>
</html>

DJLNET.WebMvc/Views/Shared/Ace/_Menubar.cshtml
<div class="sidebar" id="sidebar">
    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'fixed') } catch (e) { }
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="icon-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="icon-pencil"></i>
            </button>

            <button class="btn btn-warning">
                <i class="icon-group"></i>
            </button>

            <button class="btn btn-danger">
                <i class="icon-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- #sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li class="active open">
            <a href="#" class="dropdown-toggle">
                <i class="icon-home"></i>
                <span class="menu-text"> 系统管理 </span>

                <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu">
                <li>
                    <a href="@Url.Action("Index","User")">
                        <i class="icon-double-angle-right"></i>
                        <i class="icon-user"></i>
                        用户管理
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index","Role")">
                        <i class="icon-double-angle-right"></i>
                        <i class="icon-group"></i>
                        角色管理
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Navigate")">
                        <i class="icon-double-angle-right"></i>
                        <i class="icon-cog"></i>
                        导航管理
                    </a>
                </li>
            </ul>
        </li>
    </ul><!-- /.nav-list -->

    <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
    </div>

    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'collapsed') } catch (e) { }
    </script>
</div>

DJLNET.WebMvc/Views/Shared/Ace/_Navbar.cshtml
<div class="navbar navbar-default" id="navbar">
    <script type="text/javascript">
            try { ace.settings.check('navbar', 'fixed') } catch (e) { }
    </script>

    <div class="navbar-container" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="#" class="navbar-brand">
                <small>
                    <i class="icon-home"></i>
                    ACE后台管理系统
                </small>
            </a><!-- /.brand -->
        </div><!-- /.navbar-header -->

        <div class="navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="grey">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-tasks"></i>
                        <span class="badge badge-grey">1</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-ok"></i>
                            还有1个任务完成
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">软件更新</span>
                                    <span class="pull-right">65%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:65%" class="progress-bar "></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                查看所有任务
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="purple">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-bell-alt icon-animated-bell"></i>
                        <span class="badge badge-important">1</span>
                    </a>

                    <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-warning-sign"></i>
                            1条通知
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">
                                        <i class="btn btn-xs no-hover btn-pink icon-comment"></i>
                                        新闻评论
                                    </span>
                                    <span class="pull-right badge badge-info">+12</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                查看所有通知
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="green">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-envelope icon-animated-vertical"></i>
                        <span class="badge badge-success">1</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-envelope-alt"></i>
                            1条消息
                        </li>

                        <li>
                            <a href="#">
                                <img src="~/Content/Ace/assets/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Alex:</span>
                                        不知道写啥 ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="icon-time"></i>
                                        <span>1分钟以前</span>
                                    </span>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                查看所有消息
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="~/Content/Ace/assets/avatars/user.jpg" alt="Jason's Photo" />
                        <span class="user-info">
                            <small>欢迎光临,</small>
                            @(HttpContext.Current.User.Identity.Name??"Unkown")
                        </span>

                        <i class="icon-caret-down"></i>
                    </a>

                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="icon-cog"></i>
                                设置
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="icon-user"></i>
                                个人资料
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="@Url.Action("Logout","Home")">
                                <i class="icon-off"></i>
                                退出
                            </a>
                        </li>
                    </ul>
                </li>
            </ul><!-- /.ace-nav -->
        </div><!-- /.navbar-header -->
    </div><!-- /.container -->
</div>